[versions]
agp = "8.5.2"
anchorBottomSheetBehavior = "0.13-alpha"
androidMapsUtils = "3.4.0"
androidOtpviewPinview = "2.1.2"
audienceNetworkSdk = "6.14.0"
audienceNetworkSdkVersion = "6.15.0"
biometric = "1.2.0-alpha05"
chatWindowAndroid = "v2.2.1"
commonsLang3 = "3.12.0"
facebookLogin = "16.3.0"
firebaseAuth = "23.0.0"
firebaseMessagingVersion = "23.4.0"
floatingactionbutton = "1.10.1"
glide = "4.15.1"
gson = "2.10.1"
haishinkit = "0.13.7"
kotlin = "1.9.23"
google-services = "4.4.2"

firebaseMessaging = "24.0.2"
firebase-crashlytics = "3.0.2"
firebaseCrashlyticsVersion = "19.2.0"
firebaseAnalyticsVersion = "22.1.2"

appcompat = "1.7.0"
coreSplashscreen = "1.0.1"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinReflect = "1.9.23"
lottie = "6.4.0"
mpandroidchart = "v3.0.3"
media3 = "1.4.1"
navigationVersion = "1.0.0"
okhttp = "4.12.0"
okio = "3.9.0"
playServicesAdsVersion = "22.6.0"
playServicesAuth = "21.2.0"
playServicesLocation = "21.3.0"
playServicesLocationVersion = "21.0.1"
playServicesMaps = "19.2.0"
retrofit = "2.11.0"
shimmerrecyclerview = "v1.3"
switchbutton = "2.1.0"
libraryVersion = "2.4.0"
material = "1.12.0"
multidex = "2.0.1"
nvWebsocketClient = "2.14"
picasso = "2.71828"
playServicesAds = "23.4.0"
playServicesGcm = "17.0.0"
#playServicesMaps = "19.0.0" // TODO : libraries.navigation remove
navigation = "5.3.1"  # TODO : do not update
sdpAndroid = "1.1.0"
sspAndroid = "1.1.0"
navigationCommonAndroid = "2.9.5"

[libraries]
anchor-bottom-sheet-behavior = { module = "com.trafi:anchor-bottom-sheet-behavior", version.ref = "anchorBottomSheetBehavior" }
android-maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "androidMapsUtils" }
android-otpview-pinview = { module = "com.github.mukeshsolanki:android-otpview-pinview", version.ref = "androidOtpviewPinview" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
audience-network-sdk = { module = "com.facebook.android:audience-network-sdk", version.ref = "audienceNetworkSdk" }
audience-network-sdk-v6150 = { module = "com.facebook.android:audience-network-sdk", version.ref = "audienceNetworkSdkVersion" }
chat-window-android = { module = "com.github.livechat:chat-window-android", version.ref = "chatWindowAndroid" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalyticsVersion" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlyticsVersion" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
firebase-messaging-v2340 = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessagingVersion" }
floatingactionbutton = { module = "com.getbase:floatingactionbutton", version.ref = "floatingactionbutton" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
haishinkit = { module = "com.github.shogo4405.HaishinKit~kt:haishinkit", version.ref = "haishinkit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
navigation-v100 = { module = "com.google.android.libraries.navigation:navigation", version.ref = "navigationVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
play-services-ads-v2260 = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAdsVersion" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-location-v2101 = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
shimmerrecyclerview = { module = "com.github.sharish:ShimmerRecyclerView", version.ref = "shimmerrecyclerview" }
switchbutton = { module = "com.kyleduo.switchbutton:library", version.ref = "switchbutton" }
material = { module = "com.google.android.material:material", version.ref = "material" }
nineoldandroids-library = { module = "com.nineoldandroids:library", version.ref = "libraryVersion" }
nv-websocket-client = { module = "com.neovisionaries:nv-websocket-client", version.ref = "nvWebsocketClient" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-gcm = { module = "com.google.android.gms:play-services-gcm", version.ref = "playServicesGcm" }
#play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
navigation = { module = "com.google.android.libraries.navigation:navigation", version.ref = "navigation" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
androidx-navigation-common-android = { group = "androidx.navigation", name = "navigation-common-android", version.ref = "navigationCommonAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }