[versions]
agconnectCore = "1.6.5.300"
agp = "8.5.2"
androidOtpviewPinview = "2.1.2"
audienceNetworkSdk = "6.14.0"
biometric = "1.2.0-alpha05"
chatWindowAndroid = "v2.2.1"
counterfab = "1.2.2"
facebookLogin = "16.3.0"
firebaseAuth = "23.0.0"
flexbox = "3.0.0"
glide = "4.15.1"
gson = "2.10.1"
hmscoreinstaller = "6.6.0.300"
kotlin = "1.9.23"
google-services = "4.4.2"

firebaseMessaging = "24.0.2"
firebase-crashlytics = "3.0.2"
firebaseCrashlyticsVersion = "19.2.0"
firebaseAnalyticsVersion = "22.1.2"

appcompat = "1.7.0"
coreSplashscreen = "1.0.1"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinReflect = "1.9.23"
library = "2.1.0"
hms-location = "6.7.0.300"
likebutton = "0.2.3"
lottie = "6.4.0"
hms-maps = "6.5.1.300"
media3 = "1.4.1"
okhttp = "4.12.0"
okio = "3.9.0"
playServicesAuth = "21.2.0"
playServicesLocation = "21.3.0"
hms-push = "6.7.0.300"
retrofit = "2.11.0"
shimmerrecyclerview = "v1.3"
skyfishjyLibrary = "1.0.1"
switchbutton = "2.1.0"
libraryVersion = "2.4.0"
material = "1.12.0"
multidex = "2.0.1"
nvWebsocketClient = "2.14"
picasso = "2.71828"
playServicesAds = "23.4.0"
playServicesGcm = "17.0.0"
playServicesMaps = "19.0.0"
realmGradlePlugin = "10.18.0"
sdpAndroid = "1.1.0"
sspAndroid = "1.1.0"
stepview = "1.5.1"

[libraries]
agconnect-core = { module = "com.huawei.agconnect:agconnect-core", version.ref = "agconnectCore" }
android-otpview-pinview = { module = "com.github.mukeshsolanki:android-otpview-pinview", version.ref = "androidOtpviewPinview" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
audience-network-sdk = { module = "com.facebook.android:audience-network-sdk", version.ref = "audienceNetworkSdk" }
chat-window-android = { module = "com.github.livechat:chat-window-android", version.ref = "chatWindowAndroid" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
counterfab = { module = "com.github.andremion:counterfab", version.ref = "counterfab" }
facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebookLogin" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalyticsVersion" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlyticsVersion" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hms-location = { module = "com.huawei.hms:location", version.ref = "hms-location" }
hmscoreinstaller = { module = "com.huawei.hms:hmscoreinstaller", version.ref = "hmscoreinstaller" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
library = { module = "com.kyleduo.switchbutton:library", version.ref = "library" }
likebutton = { module = "com.github.jd-alexander:LikeButton", version.ref = "likebutton" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
hms-maps = { module = "com.huawei.hms:maps", version.ref = "hms-maps" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
hms-push = { module = "com.huawei.hms:push", version.ref = "hms-push" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
ripplebackground-library = { module = "com.skyfishjy.ripplebackground:library", version.ref = "skyfishjyLibrary" }
shimmerrecyclerview = { module = "com.github.sharish:ShimmerRecyclerView", version.ref = "shimmerrecyclerview" }
switchbutton = { module = "com.kyleduo.switchbutton:library", version.ref = "switchbutton" }
material = { module = "com.google.android.material:material", version.ref = "material" }
nineoldandroids-library = { module = "com.nineoldandroids:library", version.ref = "libraryVersion" }
nv-websocket-client = { module = "com.neovisionaries:nv-websocket-client", version.ref = "nvWebsocketClient" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-gcm = { module = "com.google.android.gms:play-services-gcm", version.ref = "playServicesGcm" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
realm-gradle-plugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realmGradlePlugin" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
stepview = { module = "com.github.shuhart:stepview", version.ref = "stepview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }